"""added seed.py

Revision ID: 55d8660c5bfd
Revises: 180e0141be92
Create Date: 2023-09-04 16:04:38.030068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d8660c5bfd'
down_revision: Union[str, None] = '180e0141be92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('customer', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'last_name')
    op.drop_column('customer', 'first_name')
    # ### end Alembic commands ###
